// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhZuLkPrAnDVGgNHAb_-gmKXyeieHz4LE',
    appId: '1:1094337432775:web:1e1029d4a74fd6050682e2',
    messagingSenderId: '1094337432775',
    projectId: 'rural-workforce-connect',
    authDomain: 'rural-workforce-connect.firebaseapp.com',
    storageBucket: 'rural-workforce-connect.firebasestorage.app',
    measurementId: 'G-TVNQRSG07G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4GfU2Z69fO_EsZtkKL6lKkrIPK54dvvQ',
    appId: '1:1094337432775:android:75b8a80e737996130682e2',
    messagingSenderId: '1094337432775',
    projectId: 'rural-workforce-connect',
    storageBucket: 'rural-workforce-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiVrvznHulDfDDC_Q8joIeLXRmHuPhaHc',
    appId: '1:1094337432775:ios:77efb58c29d7d4a30682e2',
    messagingSenderId: '1094337432775',
    projectId: 'rural-workforce-connect',
    storageBucket: 'rural-workforce-connect.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiVrvznHulDfDDC_Q8joIeLXRmHuPhaHc',
    appId: '1:1094337432775:ios:77efb58c29d7d4a30682e2',
    messagingSenderId: '1094337432775',
    projectId: 'rural-workforce-connect',
    storageBucket: 'rural-workforce-connect.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhZuLkPrAnDVGgNHAb_-gmKXyeieHz4LE',
    appId: '1:1094337432775:web:72019b41079ca3000682e2',
    messagingSenderId: '1094337432775',
    projectId: 'rural-workforce-connect',
    authDomain: 'rural-workforce-connect.firebaseapp.com',
    storageBucket: 'rural-workforce-connect.firebasestorage.app',
    measurementId: 'G-FFBZ6CTM5C',
  );
}
